-- Editable BDTT organization metadata for the dedicated personnel chart.
-- Apply after the existing profile/auth migrations.

alter table public.profiles
  add column if not exists org_group text,
  add column if not exists subgroup text,
  add column if not exists org_role text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_org_role_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_org_role_check
      check (
        org_role is null
        or org_role in (
          'toTruong',
          'nhomTruong',
          'nhomPho',
          'pnt',
          'member',
          'supervisor'
        )
      );
  end if;
end
$$;

create table if not exists public.bdtt_personnel_org_audit (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  changed_by uuid not null references public.profiles(id),
  before_state jsonb not null,
  after_state jsonb not null,
  changed_at timestamptz not null default now()
);

create index if not exists bdtt_personnel_org_audit_profile_idx
  on public.bdtt_personnel_org_audit (profile_id, changed_at desc);

alter table public.bdtt_personnel_org_audit enable row level security;

create or replace function public.update_bdtt_personnel_org(
  actor_profile_id uuid,
  target_username text,
  next_org_group text,
  next_subgroup text,
  next_org_role text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_username text;
  target_profile public.profiles%rowtype;
  normalized_group text := trim(coalesce(next_org_group, ''));
  normalized_subgroup text := trim(coalesce(next_subgroup, ''));
  normalized_role text := trim(coalesce(next_org_role, ''));
  next_app_role text;
  before_payload jsonb;
  after_payload jsonb;
begin
  select lower(trim(username))
  into actor_username
  from public.profiles
  where id = actor_profile_id
    and is_active = true;

  if actor_username is null or actor_username not in ('vinhlpp', 'kiaq') then
    raise exception 'Personnel organization management is restricted';
  end if;

  if normalized_group = '' then
    raise exception 'Organization group is required';
  end if;

  if normalized_role not in (
    'toTruong',
    'nhomTruong',
    'nhomPho',
    'pnt',
    'member',
    'supervisor'
  ) then
    raise exception 'Invalid organization role';
  end if;

  if normalized_role in ('toTruong', 'nhomTruong', 'nhomPho', 'supervisor') then
    normalized_subgroup := '';
  end if;

  if normalized_role = 'pnt' and normalized_subgroup = '' then
    raise exception 'Subgroup is required for PNT';
  end if;

  select *
  into target_profile
  from public.profiles
  where lower(trim(username)) = lower(trim(target_username))
    and is_active = true
  for update;

  if target_profile.id is null then
    raise exception 'Target profile was not found';
  end if;

  before_payload := jsonb_build_object(
    'username', target_profile.username,
    'role', target_profile.role,
    'orgGroup', target_profile.org_group,
    'subgroup', target_profile.subgroup,
    'orgRole', target_profile.org_role
  );

  next_app_role := case
    when lower(trim(target_profile.username)) = 'vinhlpp' then 'admin'
    when normalized_role = 'member' then 'worker'
    else 'admin'
  end;

  update public.profiles
  set
    role = next_app_role,
    org_group = normalized_group,
    subgroup = normalized_subgroup,
    org_role = normalized_role
  where id = target_profile.id;

  after_payload := jsonb_build_object(
    'username', target_profile.username,
    'role', next_app_role,
    'orgGroup', normalized_group,
    'subgroup', normalized_subgroup,
    'orgRole', normalized_role
  );

  insert into public.bdtt_personnel_org_audit (
    profile_id,
    changed_by,
    before_state,
    after_state
  ) values (
    target_profile.id,
    actor_profile_id,
    before_payload,
    after_payload
  );

  return after_payload;
end;
$$;

revoke all on function public.update_bdtt_personnel_org(uuid, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.update_bdtt_personnel_org(uuid, text, text, text, text)
  to service_role;
